### ISSUE TITLE
import entries only

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-import#14]
The contentful-import does not support the import of entries only.

This would be very handy when exporting/importing spaces and only the entries are important. Assets take too much space and may not fit within the free/paid subscription model at the time.

Is there an alternative workaround to get this to work?

**Comment by Khaledgarbaya** [comment]
Hi @temelj ,

It is in the roadmap to have flags for what to import but unfortunately, I don't have a clear timeline for this feature. [This](https://github.com/contentful/contentful-batch-libs/blob/master/lib/push/push-to-space.js) is the part that does the import, it shouldn't be so hard to achieve that if your need is urgent for now.

I'll keep you posted whenever this issue is resolved.
Best,
Khaled

**Comment by temelj** [comment]
Hi,

thank you for your reply.  The limitation with the asset space requirement was part of the previous "Free" Plan. We had a few legacy plans hanging around and as they were asset count limited, an import was required without the assets.  This is sorted now.

**Comment by temelj** [comment]
I would like to further contribute to this:

We needed some tests on import/export and having to import 1000+ assets, it slowed down the testing which would make this feature enhancement rather handy.

The workaround is to manually edit the exported.json file and remove the "assets" content.

Your file should look as follows:
```
{
"contentTypes": [ do not edit ],

"entries": [ do not edit ],

"assets": [ delete everything including the curly braces ],

and so on
}
```
