### ISSUE TITLE
Question: importing data into space with existing (matching) entries

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-import#19]
I'm wondering from the contentful-import library point of view, if I have an existing destination space with some existing content types and entries,  when contetnful-import is called containing a json document with already used entry.sys.spaceid, does the data get completely overwritten or does the existing entry get updated with the field values from the json document?

**Comment by Khaledgarbaya** [comment]
hi @temelj, the contentful-import tool is using the management SDK's [createEntryWithId()](https://github.com/contentful/contentful-management.js/blob/master/lib/create-space-api.js#L415) which as you can see in the code it uses `PUT`, when our endpoint receives a put request it checks if the entry exists it update it otherwise it creates a new one.

**Comment by temelj** [comment]
Thank you Khaled,  this explains the behavior that I've observed.
Sorry, I didn't follow the code on this one.  I noticed this when I created a bunch of entries using createEntryWithId() method and then when I used contentful-import it would retain the original entry, but update it with the field data.
