### ISSUE TITLE
Assistance w/ importing a json file to Contentful. 

### ISSUE THREAD

**Issue by Nappstir** [contentful/contentful-import#75]
I currently took data from a `.sql` file and converted it to `.csv`, to which I then converted that `.csv` file into `.json` data. I am now trying to import that into Contentful. Here is the following command I am running: 

`contentful-import --space-id "spaceID" --management-token "accessToken" --content-file "data.json"`

Here is the following response that I get: 
<img width="924" alt="screen shot 2017-12-21 at 3 39 42 pm" src="https://user-images.githubusercontent.com/10201131/34277976-4d70a738-e665-11e7-92c4-df88c033b1a4.png">

Here is the stacktrace:
<img width="1199" alt="screen shot 2017-12-21 at 3 50 11 pm" src="https://user-images.githubusercontent.com/10201131/34278202-aa6b9442-e666-11e7-8634-c3d2789299a7.png">

My first question would be to make sure that for `--management-token` I pass in my spaces Content Delivery API - access token found on the API tab? 

Second question would be if my json has to be in a specific format? It is just an array of objects with the same keys and different values. Here is a sample of what it looks like: 
<img width="597" alt="screen shot 2017-12-21 at 3 50 52 pm" src="https://user-images.githubusercontent.com/10201131/34278225-c47cae16-e666-11e7-8797-a4cd1ab887b7.png">

I'm just wondering if I am missing something here because it seems to me that no one else is having an issue with importing a json file. Is it that my json objects need to be structured like the json objects provided by the Contentful api when accessing it?

**Comment by Khaledgarbaya** [comment]
Hi @Nappstir,
1. the `--management-token` is the read and write token and it is not the content Delivery token 
you need to click on APIS --> content management tokens tab
Check screenshot.

![screen shot 2017-12-22 at 14 11 23](https://user-images.githubusercontent.com/1156093/34299226-155d0d7e-e722-11e7-8448-283798264e52.png)

2.you need to structure your json in a format that `content-import` tool understand. you can check and example [here](https://github.com/contentful/contentful-import/blob/master/test/integration/sample-space.json) you can write a script that transforms that data to the import format and then pass to the tool since you can us it also as a node library.

Best,
Khaled

**Comment by axe312ger** [comment]
Hey there,

another thing that could help you:

1. create a content-model in our web app/via the [migration-cli](https://github.com/contentful/migration-cli) that matches your data
2. add one example entry for every type
3. export your space via contentful-export
4. use that file structure as blueprint to write your data transformations as Khaled mentioned above
5. import your transformed json file to import it via contentful-import

Cheers,
Benedikt

**Comment by axe312ger** [comment]
@Nappstir Did it work out for you? :)

**Comment by Nappstir** [comment]
@axe312ger Yes! I was able to figure out the management token just as you had posted that answer. After that, I built a mock of what I wanted the data to look like and exported it. Once I saw how contentful wanted the json to be formatted I was able to get it to work from there. 

Thank you!
