### ISSUE TITLE
Issues with the proxy flag

### ISSUE THREAD

**Issue by christineywang** [contentful/contentful-import#85]
Hello,

We are having issues importing content using the `--proxy` option.

Here is the flag we are using (some values have been changed):
`--proxy proxy.something.com:3333`

<br>

The entire command looks like this:
```
contentful-import \
  --space-id spaceID \
  --management-token managementToken \
  --content-file exported-file.json \ 
  --proxy xyz
```
<br>

When we use the proxy option, the import fails on this line:
```
x Importing Editor Interfaces (3s) 
→ TypeError [ERR_INVALID_ARG_TYPE]: The "Agent option" argument must be on
```
<br>

We are able to import content when we don't use the proxy option and the proxy option works when we use the export tool. 

Can you give us more insight as to what the error message means when we are trying to import content with the proxy option? Do we need to set something like `"secureProxy": true` somewhere?

Thanks!

**Comment by axe312ger** [comment]
Hey Christine,

you are using it the right way 😱 

The error message is not coming from our tools. It must be from on of our dependencies or node itself. A quick look at google actually didn't give to much information. I have to look more detailed.

You gave me a part of your output, is my assumption correct, that importing of locales, content types and publishing of content types worked fine and it broke when importing editor interfaces?

The import of editor interfaces is a little bit special, so that might be the issue here. Can you please clarify? :)

Thanks,
Benedikt

**Comment by christineywang** [comment]
Hi @axe312ger,

Yes, I believe everything before `Importing Editor Interfaces` worked (I didn't test this out myself with a proxy flag).

What the user sent me was where the import failed and all the succeeding actions that couldn't be completed:

```
x Importing Editor Interfaces (3s) 
→ TypeError [ERR_INVALID_ARG_TYPE]: The "Agent option" argument must be on

Importing Assets 
Publishing Assets 
Archiving Assets 
Importing Content Entries 
Publishing Content Entries 
Archiving Entries 
Creating Web Hooks
```

Thanks!

**Comment by axe312ger** [comment]
So I checked the code, Editor Interfaces are handled differently, but they get the proxy settings passed.

@christineywang I need more details about the proxy, the setup and the actual proxy configuration.

Please open a support ticket and we will continue over there since I might need sensitive data to properly solve this.

Thanks a lot,
Benedikt

**Comment by christineywang** [comment]
Got it!

I will escalate the internal ticket once I get more information from the user. Thanks!
